corednsdeploymentname: ${corednsdeploymentname}
minReplicas: ${minReplicas}
maxReplicas: ${maxReplicas}
targetCPUUtilizationPercentage: ${targetCPUUtilizationPercentage}
targetMemoryUtilizationPercentage: ${targetMemoryUtilizationPercentage}
